apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: platform-one
spec:
  ## Platform
  image_pull_policy: IfNotPresent
  no_log: false
  controller:
    disable: false
  eda:
    disable: false
  hub:
    disabled: false
    storage_type: S3
    object_storage_s3_secret: s3-secret
  lightspeed:
    disabled: true
